name: package

on:
  release:
    types: [published]

jobs:
  build_sdist:
    name: Build SDist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx run build --sdist
      - run: pipx run twine check dist/*
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  pypi-publish:
    name: Upload release to PyPI
    needs: [build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
